import type { Metadata } from "next";
import { Onest, Figtree } from "next/font/google";
import "./globals.scss";
import StoreProvider from "@/app/_components/Store/StoreProvider";

const inter = Onest({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <StoreProvider>
          <main className="bg-gray-50 min-h-screen w-screen">
              {children}
          </main>
      </StoreProvider>

      </body>
    </html>
  );
}
